from __future__ import annotations

from typing import Any, Dict

from fem_refactor.models import ConfigValues


def build_config_values(
    *,
    config: Dict[str, Any],
    roi_default: Dict[str, Any],
    extension_params: Dict[str, Any],
    roi3_extension_params: Dict[str, Any],
    save_roi1: bool,
    save_roi2: bool,
    save_roi3: bool,
    save_wave: bool,
    save_roi1_wave: bool,
    only_delect: bool,
    threshold: float,
    threshold_minimum: float,
    margin_frames: int,
    diff_threshold: float,
    silence_frames: int,
    pre_post_avg_frames: int,
    min_region_length: int,
    adaptive_threshold_enabled: bool,
    threshold_over_mean_ratio: float,
    adaptive_window_seconds: float,
    adaptive_window_frames: int,
    protection_enabled: bool,
    recovery_delay_seconds: float,
    recovery_delay_frames: int,
    stability_frames: int,
    waveform_trigger_enabled: bool,
    roi1_enabled: bool,
    roi1_threshold: float,
    roi1_threshold_minimum: float,
    roi1_margin_frames: int,
    roi1_silence_frames: int,
    roi1_pre_post_avg_frames: int,
    roi1_difference_threshold: float,
    roi1_min_region_length: int,
    roi1_adaptive_threshold_enabled: bool,
    roi1_threshold_over_mean_ratio: float,
    roi1_adaptive_window_seconds: float,
    roi1_protection_enabled: bool,
    roi1_recovery_delay_seconds: float,
    roi1_stability_frames: int,
    roi1_waveform_trigger_enabled: bool,
    hybrid_enabled: bool,
    roi2_pre_frames: int,
    roi2_post_frames: int,
    min_roi2_frames: int,
    roi2_min_variance: float,
    fallback_enabled: bool,
    max_peak_width: int,
    data_quality_conf: Dict[str, Any],
    hybrid_conf: Dict[str, Any],
    g1_g2_override_enabled: bool,
    g1_threshold: float,
    g2_threshold: float,
    use_peak_max_g1_g2: bool,
) -> ConfigValues:
    return ConfigValues(
        raw=config,
        roi_default=roi_default,
        extension_params=extension_params,
        roi3_extension_params=roi3_extension_params,
        save_roi1=save_roi1,
        save_roi2=save_roi2,
        save_roi3=save_roi3,
        save_wave=save_wave,
        save_roi1_wave=save_roi1_wave,
        only_delect=only_delect,
        threshold=threshold,
        threshold_minimum=threshold_minimum,
        margin_frames=margin_frames,
        diff_threshold=diff_threshold,
        silence_frames=silence_frames,
        pre_post_avg_frames=pre_post_avg_frames,
        min_region_length=min_region_length,
        adaptive_threshold_enabled=adaptive_threshold_enabled,
        threshold_over_mean_ratio=threshold_over_mean_ratio,
        adaptive_window_seconds=adaptive_window_seconds,
        adaptive_window_frames=adaptive_window_frames,
        protection_enabled=protection_enabled,
        recovery_delay_seconds=recovery_delay_seconds,
        recovery_delay_frames=recovery_delay_frames,
        stability_frames=stability_frames,
        waveform_trigger_enabled=waveform_trigger_enabled,
        roi1_enabled=roi1_enabled,
        roi1_threshold=roi1_threshold,
        roi1_threshold_minimum=roi1_threshold_minimum,
        roi1_margin_frames=roi1_margin_frames,
        roi1_silence_frames=roi1_silence_frames,
        roi1_pre_post_avg_frames=roi1_pre_post_avg_frames,
        roi1_difference_threshold=roi1_difference_threshold,
        roi1_min_region_length=roi1_min_region_length,
        roi1_adaptive_threshold_enabled=roi1_adaptive_threshold_enabled,
        roi1_threshold_over_mean_ratio=roi1_threshold_over_mean_ratio,
        roi1_adaptive_window_seconds=roi1_adaptive_window_seconds,
        roi1_protection_enabled=roi1_protection_enabled,
        roi1_recovery_delay_seconds=roi1_recovery_delay_seconds,
        roi1_stability_frames=roi1_stability_frames,
        roi1_waveform_trigger_enabled=roi1_waveform_trigger_enabled,
        hybrid_enabled=hybrid_enabled,
        roi2_pre_frames=roi2_pre_frames,
        roi2_post_frames=roi2_post_frames,
        min_roi2_frames=min_roi2_frames,
        roi2_min_variance=roi2_min_variance,
        fallback_enabled=fallback_enabled,
        max_peak_width=max_peak_width,
        data_quality_conf=data_quality_conf,
        hybrid_conf=hybrid_conf,
        g1_g2_override_enabled=g1_g2_override_enabled,
        g1_threshold=g1_threshold,
        g2_threshold=g2_threshold,
        use_peak_max_g1_g2=use_peak_max_g1_g2,
    )

