"""
完整数据流追踪：ROI2判定 -> ROI3覆盖 -> CSV写入
"""

print("=" * 80)
print("数据流路径分析")
print("=" * 80)

print("\n1. ROI2颜色判定 (simple_roi_daemon.py)")
print("-" * 80)
print("位置: 第753行")
print("代码: color = \"green\" if frame_difference >= color_threshold else \"red\"")
print("输出: hybrid_peak字典包含 'color' 键")
print()
print("示例:")
print("  frame_difference = -0.072")
print("  color_threshold = 1.5")
print("  frame_difference < color_threshold  =>  color = 'green' ✓")
print()

print("2. 传递到统计系统 (simple_roi_daemon.py:1918)")
print("-" * 80)
print("代码: current_stats.add_peaks_from_daemon(")
print("        ...,")
print("        hybrid_enabled=True,")
print("        hybrid_peaks=hybrid_peaks,  # ← 包含'color'键")
print("        roi3_curve=list(roi3_gray_buffer),")
print("        roi3_override_enabled=True,")
print("        roi3_override_threshold=111.0")
print("    )")
print()

print("3. ROI3覆盖逻辑 (safe_peak_statistics.py:479-554)")
print("-" * 80)
print("位置: _create_hybrid_peak_data 函数")
print()
print("3.1 读取初始颜色 (第479行):")
print("  color = hybrid_peak.get('color', 'unknown')")
print("  final_peak_type = color  # ← 初始为 green")
print()
print("3.2 ROI3覆盖条件 (第531-552行):")
print("  if roi3_curve and roi3_override_enabled:")
print("      # 计算ROI3峰值位置")
print("      roi3_peak_max_frame = curve_start_global_frame + roi3_max_curve_idx")
print()
print("      # RED -> GREEN 覆盖")
print("      if final_peak_type == \"red\" and roi3_peak_max > threshold:")
print("          final_peak_type = \"green\"")
print()
print("      # GREEN -> RED 覆盖 (第549行)")
print("      elif final_peak_type == \"green\" and roi3_peak_max_frame < 110:")
print("          final_peak_type = \"red\"  # ← 应该触发")
print()
print("3.3 返回最终数据 (第557-572行):")
print("  hybrid_data = {")
print("      'peak_type': final_peak_type,  # ← 覆盖后的颜色")
print("      'roi3_peak_max_value': roi3_peak_max,")
print("      'roi3_peak_max_frame': roi3_peak_max_frame,")
print("      ...")
print("  }")
print()

print("4. 写入CSV (safe_peak_statistics.py)")
print("-" * 80)
print("位置: _write_peak_to_csv 函数")
print("代码: writer.writerow({")
print("    'peak_type': peak_data['peak_type'],  # ← 使用覆盖后的颜色")
print("    'roi3_peak_max_frame': peak_data['roi3_peak_max_frame'],")
print("    ...")
print("})")
print()

print("=" * 80)
print("问题诊断")
print("=" * 80)
print()
print("检查点:")
print("1. ROI2是否判定为绿色? ✓ CSV显示 peak_type=green")
print("2. ROI3曲线是否为空? 需要检查 roi3_curve_len")
print("3. roi3_override_enabled是否为True? 需要检查")
print("4. roi3_peak_max_frame计算是否正确? 需要检查")
print("5. 条件 roi3_peak_max_frame < 110 是否满足? ✓ 81 < 110")
print()
print("可能的问题:")
print("- roi3_curve为空列表 []")
print("- roi3_override_enabled实际为False")
print("- 代码路径错误，没有执行到ROI3覆盖")
print()
print("建议: 添加调试日志后重新运行，查看 [DEBUG ROI3] 输出")
